### ISSUE TITLE
Inconsistency in docu

### ISSUE THREAD

**Issue by jsPlachetka** [cloudfoundry-incubator/bpm-release#102]
Looking at https://bosh.io/docs/bpm/runtime/ and https://github.com/cloudfoundry-incubator/bpm-release/blob/master/docs/config.md we found a inconsistency in the documentation.
For shared data different key words are given (volumes vs additional_volumes) and even the explanation how to use it is misleading.

**Comment by voelzmo** [comment]
Thanks @jsPlachetka for raising this issue! I have opened #103 to address the incorrect key in the docs. 

Could you help me understand on where the documentation for `additional_volumes` was misleading you, such that we can address this as well?

Thanks!

**Comment by kramerul** [comment]
Hi Marco,

@jsPlachetka  asked me to answer your question. We had 2 problems with the documentation in https://github.com/cloudfoundry-incubator/bpm-release/blob/master/docs/config.md

* It was not clear, that we need to enter a compete path as volume
* It was not clear, that it this is a BPM setting and not part of the jobs configuration. We first tried to change the jobs configuration.

Regards
Ulrich
