### ISSUE TITLE
Expose the job's socket directory with a single configuration option

### ISSUE THREAD

**Issue by xoebus** [cloudfoundry-incubator/bpm-release#107]
The same way we have `ephemeral_disk:` and `persistent_disk:` to mount in a default volume for the current job we could have the same for the socket directory.

The first pass proposal for this was to add `sockets:` but @jfmyers9 wasn't a fan.

/cc @aramprice @jfmyers9

**Comment by xoebus** [comment]
I'd like to make a 0.13.0 release but would like to make sure that this has at least been considered before that point.

**Comment by jfmyers9** [comment]
I don't mind adding something similar, I just personally feel like `sockets:` is just one of many use cases for using `/var/vcap/sys/run`. Haven't been able to come up with a better name yet, still thinking on it.

**Comment by xoebus** [comment]
Not important enough.
