### ISSUE TITLE
Config Documentation is Incorrect

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry-incubator/bpm-release#11]
Example Documentation for Config
https://github.com/cloudfoundry-incubator/bpm-release/blob/21958b5/docs/config.md#job-configuration

Shows that `<job>` and `<worker>` are keys. Looking at the source code it reveals that the processes is an array, and that the job name is part of `name`

It seems that this is a more accurate configuration, but it's hard to tell

    processes:
    - name: uaa
      executable: /var/vcap/jobs/uaa/bin/uaa
      env:
        CATALINA_BASE: /var/vcap/data/uaa/tomcat
        CATALINA_HOME: /var/vcap/data/uaa/tomcat
        CLOUD_FOUNDRY_CONFIG_PATH: /var/vcap/jobs/uaa/config
        CATALINA_OPTS: "-Xmx768m -XX:MaxMetaspaceSize=256m"
      args: []

**Comment by aramprice** [comment]
There's a pending PR which should fix the doc issues https://github.com/cloudfoundry-incubator/bpm-release/pull/18

**Comment by drnic** [comment]
#18 has been merged now

**Comment by aramprice** [comment]
@fhanik is it ok to close this based on the updates from #18 ?
