### ISSUE TITLE
creation of pre-defined files?

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry-incubator/bpm-release#113]
We'd like to be able to setup a file, say for access logging, in some well known location. For now, the only way there seems to be able to do this is to actually have a pre-start script that creates said file. Would be nicer if bpm could make a known file for us if requested.

**Comment by xoebus** [comment]
You should be able to create the file from inside your BPM job. I've done this before with access logs at `/var/vcap/sys/log/JOB/access.log`.

Can you give more details about the use case? I think I'm missing something.

**Comment by xoebus** [comment]
Closing as inactive - hit us up on Slack if you still think there's a missing feature here.
