### ISSUE TITLE
Delete bpm/mounts package

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry-incubator/bpm-release#115]
Hi there!

It looks like the bpm/mounts package can be deleted since the three functions within that package already exist within bpm dependenies.

mount.Mount -> unix.Mount
mount.Unmount -> unix.Unmount
mount.Mounts -> github.com/opencontainers/runc/libcontainer/mount.GetMounts()

I would have PRed this but before I do I wanted to find out about vendoring methods in bpm. It looks like github.com/opencontainers/runc/libcontainer/mount isn't venored right now, and when I try to add the import path to bpm/cgroups (instead using runc's GetMounts()) and run `dep ensure`, it's making changes to a large numer of files. I had a look at the Gopkg.lock and it looks like you've vendored 0.1.1 of runc and I assume my dep ensure was trying to update runc since the runc mount package didn't exist in 0.1.1.

Looking at the commits to the bosh packages, it looks like you're currently packaging 1.0.0-rc6 - perhaps the runc library being used should be kept in sync with the binary bpm builds.

Additionally I can see that the version of runc is not locked in the Gopkg.toml - would you accept two PRs to:

1. lock the version of the runc library, and bump to 1.0.0-rc6
2. delete the bpm/mount package in favour of libcontainer/mount

**Comment by xoebus** [comment]
I've updated the RunC library to 1.0.0.-rc6

**Comment by xoebus** [comment]
The `ParseFstab` function is now only used in a test and can be moved to that test.

**Comment by BooleanCat** [comment]
Nice thanks, I'll PR this when I get time this week.

I've also PRed runc to expose their /proc/self/mountinfo logic that takes a reader rather than hardcoding the file path - so we may not even need ParseFstab at all in the near future.
