### ISSUE TITLE
Feature request - `pre-stop`

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry-incubator/bpm-release#12]
Currently we have to do some [very elaborate bash](https://github.com/cloudfoundry/uaa-release/blob/ab0a291588f2617c8c1b562d20c711425ff3b737/jobs/uaa/templates/bin/uaa.erb#L30-L48) scripting to make sure we can trap signals and coordinate with other jobs on the VM in [uaa-release](https://github.com/cloudfoundry/uaa-release/blob/ab0a291588f2617c8c1b562d20c711425ff3b737/jobs/uaa/templates/bin/uaa.erb#L30-L48).

It would be nice if BPM provided a `pre-stop` hook. 

The UAA, runs as a Java web application on a servlet container. Today we don't have a way to intercept signals in the Java process before the container, Apache Tomcat, starts shutting down. 

_This feature request may become obsolete once we move to Spring Boot, where we could control the shutdown sequence ourselves._

**Comment by cppforlife** [comment]
@fhanik bin/drain doesnt help?

**Comment by aramprice** [comment]
@fhanik we've been chewing on this for a bit and I don't think we'll be adding a `pre-stop` hook. hopefully the Spring Boot update will resolve this in the long run, or perhaps @cppforlife's suggestion of using `drain` work for you all. Going to close this out.
