### ISSUE TITLE
Submodule Bumper is chatty, but not informative

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#19]
![screen shot 2017-10-24 at 10 36 47 am](https://user-images.githubusercontent.com/108/31919645-49c675c2-b8a7-11e7-8729-cb01cf4198bc.png)

Could Submodule Bumper be updated to specify what submodules it updated in the commit message?

**Comment by jfmyers9** [comment]
Hopefully this is better as of 36efa919c7df487ac390e4b2a901131f741f4e82. Closing for now. Feel free to reopen.
