### ISSUE TITLE
Can we break BPM into a submodule with properly vendored dependencies?

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry-incubator/bpm-release#27]
Is this something we want to do? I opened this issue as a place for discussion. I don't believe this is something urgent that we need to solve now, but I would like to hear thoughts and opinions.

Pros:
* We can vendor our dependencies in a standard way i.e. `dep`
* BPM can be built outside of the BOSH releases context and encodes it's own dependencies.
* BPM code can be imported into other codebases (may not be valuable)

Cons:
* Our tooling is built around submodules (bumping dependencies, commit messages, etc)
* BPM as a tool never needs to be built outside of a BOSH release.
* We would have a separate repository for the code.

Thoughts?

**Comment by loewenstein** [comment]
> * BPM as a tool never needs to be built outside of a BOSH release.

At least the [definition of bpm.yml](https://github.com/cloudfoundry-incubator/bpm-release/blob/master/src/bpm/config/job_config.go) could be interesting outside a BOSH release if someone would want to schedule BPM defined jobs on a different scheduler.

**Comment by aramprice** [comment]
I really like the idea of being able to use `dep`. I think it would be worth exploring whether there's a viable way to do that within a bosh release, allowing is to sidestep the need for a submodule.

This is a pattern many other teams use but having code split across submodules is a tax on productivity, except perhaps where that code is shared between many projects.

**Comment by jfmyers9** [comment]
Even if we use `dep` while keeping it in the same repository, the golang code for `bpm` is very hard to import into other projects. This is because `bpm-release` is a `GOPATH` and currently `bpm` imports itself as a top-level import. This would be fundamentally incompatible with how users would have to import our project i.e. `import "github.com/cloudfoundry-incubator/bpm-release/src/bpm"`. I think no matter where we move `bpm` on the `bpm-release` `GOPATH` this is still an issue due to the fact that golang's importing scheme is so closely tied to version control.

As said this may not be a supported use case, but as @loewenstein pointed out, there are use cases such as people importing `bpm` for accessing it's configuration struct declarations.

**Comment by aramprice** [comment]
That makes sense. I was kicking around an idea that we might be able to satisfy both the bosh-release directory layout, as well as the golang directory layout with some clever hack.

Seems like we should just bite the bullet and spin out a submodule for the bpm go code.

**Comment by xoebus** [comment]
We were just about to make changes to the configuration package today which would have caused a breaking change. I don't think we're ready to expose these as a stable interface yet. I'd like to propose that if we do this that we do it as one of the final steps before 1.0.

:+1: on switching to `dep` as an incremental step inside our own release

:-1: (at the moment) of declaring parts of this as part of the public interface

**Comment by cppforlife** [comment]
> I really like the idea of being able to use dep. I think it would be worth exploring whether there's a viable way to do that within a bosh release, allowing is to sidestep the need for a submodule.

we use dep in bosh-dns-release (https://github.com/cloudfoundry/bosh-dns-release/tree/master/src/bosh-dns). no problem afaik.

**Comment by xoebus** [comment]
We have switched to dep in the latest release (you shouldn't notice any difference). I hope we can extract the main code repository (which should be trivial now) closer to 1.0.

**Comment by jfmyers9** [comment]
I'm closing this as I don't see a pressing need to solve this.

If there are consumers that want to consume bpm as a dependency, feel free to comment / open a new issue to address this.
