### ISSUE TITLE
bosh.io/docs presence

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bpm-release#40]
it would be nice to add a page to bosh.io/docs to describe that we recommend bpm and how we typically expect people to use it. may be also list options (similar to http://bosh.io/docs/package-vendoring.html) when to use it and when not to.

**Comment by jfmyers9** [comment]
Closing as the docs appear to be available at: http://bosh.io/docs/bpm/bpm/

**Comment by drnic** [comment]
yay!
