### ISSUE TITLE
bpm pre-start question

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-incubator/bpm-release#44]
If I reboot vm, bpm pre-start will not be run and cgroup will not be mounted?

**Comment by jfmyers9** [comment]
Hey @marcus-sds,

Thanks for bringing this to our attention. This is definitely an issue.

I've spoken with @xoebus and we think there might be a path forward by moving this check/functionality into the `bpm` binary itself.

Best,

@jfmyers9
