### ISSUE TITLE
Please cut github releases

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#46]
Can you please cut github releases for each new version - this will trigger GitHub to send emails to everyone who is watching; and we'll know that there is a new version. All my releases are still on 0.2.0 and just noticed there is now an 0.4.0.

Bonus question: what's changed between 0.2.0 and 0.4.0? Can I just upgrade or do I need to change my `bpm.yml`?

**Comment by jfmyers9** [comment]
I agree and we can add a step in our concourse build to cut a github release and add some release notes on each final version.

With regards to your second question, you should be able to upgrade from `0.2.0` -> `0.4.0` with no changes.

**Comment by jfmyers9** [comment]
Hey @drnic,

We will be cutting github releases from now on. We also have a running `CHANGELOG.md` in the root of the repository that will be tracking features, bugs, and behavior changes.

Best,

@jfmyers9
