### ISSUE TITLE
Read-only log dir mounting for log-forwarding add-ons?

### ISSUE THREAD

**Issue by anEXPer** [cloudfoundry-incubator/bpm-release#47]
We recently discovered that we're running blackbox in the syslog-release with `cap_dac_read_search` [in our ctl script](https://github.com/cloudfoundry/syslog-release/blob/bd29a78cba03644081e6108b4cbec83277010b15/jobs/syslog_forwarder/templates/blackbox_ctl.erb#L21). Permissions around log files as currently written by current releases are inconsistent/inconvenient, so we need this for our `vcap` process to read pre-start logs as root, etc.

So we were thinking it might be good to constrain that ability to read from the entire filesystem.
We've got thoughts on forming an explicit contract about file permissions in the future, but for now/soontimes, we were thinking maybe BPM could let us run blackbox with that `cap`, but only mount the `/var/vcap/sys/log` directory. Of course, this isn't part of your interface right now that I can see.

We'd ideally get it as a read only mount.

(Also, would that setcap still work/be available in BPM? Changing the user removes caps, but if it were set after the user...)

**Comment by voelzmo** [comment]
+1 It would be great if blackbox didn't need to run on the VM directly, but could also run in a container.

**Comment by xoebus** [comment]
This should now be possible by using the new [unrestricted volumes feature](https://github.com/cloudfoundry-incubator/bpm-release/commit/23422fbec3a6e377b8b94b2dfbb6cfd2d9492ed9). Could you give that a try and let us know if it works for you?

**Comment by anEXPer** [comment]
It probably solves not being able to run blackbox in BPM at all, don't know when I'll be able to try it (syslog is not currently allocated engineering team, so I'm working on it as a flex project).

I don't see any provision to have read-only access, did I just miss that, or is it not part of this yet?

**Comment by xoebus** [comment]
It's read-only by default and then you can opt a volume in to being writable.

**Comment by anEXPer** [comment]
Cool, that should work exactly the way we want it, thanks.
