### ISSUE TITLE
Publish pre-compiled releases

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#49]
Could bpm CI please start publishing pre-compiled releases? Currently, a no-op bosh release with `bpm` addon takes 5 mins on a bosh-lite/bucc-lite to compile golang/bpm:

```
Task 4 | 01:08:43 | Compiling packages: bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85
Task 4 | 01:08:43 | Compiling packages: golang/65c792cb5cb0ba6526742b1a36e57d1b195fe8be
Task 4 | 01:10:34 | Compiling packages: bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85 (00:01:51)
Task 4 | 01:11:21 | Compiling packages: golang/65c792cb5cb0ba6526742b1a36e57d1b195fe8be (00:02:38)
Task 4 | 01:11:21 | Compiling packages: bpm/b5e1678ac76dd5653bfa65cb237c0282e083894a (00:00:17)
```

An example pipeline PR for adding compiled release generation + `use-compiled-releases.yml` operator file updates is https://github.com/starkandwayne/pipeline-templates/pull/28/files

**Comment by xoebus** [comment]
I'd like this too but I don't like the trade-off which compiled releases force on the release author at the moment.

I'm pushing to make this better in https://github.com/cloudfoundry/bosh/issues/1946. I'd prefer to get that feature done first and then make *only* compiled releases.

**Comment by h4xnoodle** [comment]
BPM is now compiled along with every stemcell bump for [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment). 

+1 on https://github.com/cloudfoundry/bosh/issues/1946 @xoebus 

This can now be closed if the auto bump for each new stemcell in bosh-deployment solves this issue. (I can't close it)

**Comment by xoebus** [comment]
@h4xnoodle Neat - thank you!
