### ISSUE TITLE
Missing start errors in bpm.log?

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry-incubator/bpm-release#58]
Hi - I'm not sure if this is expected or not, but I had a misconfiguration in my job's BPM stuff which was causing a failure, but the only way to discover it was by manually running `bpm start` myself. Given I was able to see messages from `bpm.log`, I initially expected to see the error message to show up there.

Initially, I tailed the job's `bpm.log`, but found nothing useful...

```
$ tail /var/vcap/sys/log/ipfs/bpm.log
{"timestamp":"1527679613.576059580","source":"bpm","message":"bpm.start.acquiring-lifecycle-lock.starting","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1.1"}}
{"timestamp":"1527679613.576259851","source":"bpm","message":"bpm.start.acquiring-lifecycle-lock.complete","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1.1"}}
{"timestamp":"1527679613.576652765","source":"bpm","message":"bpm.start.starting","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1"}}
{"timestamp":"1527679613.588210583","source":"bpm","message":"bpm.start.start-process.starting","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1.2"}}
{"timestamp":"1527679613.588368654","source":"bpm","message":"bpm.start.start-process.creating-job-prerequisites","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1.2"}}
{"timestamp":"1527679613.589195251","source":"bpm","message":"bpm.start.start-process.complete","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1.2"}}
{"timestamp":"1527679613.589248419","source":"bpm","message":"bpm.start.complete","log_level":1,"data":{"job":"ipfs","process":"ipfs","session":"1"}}
```

After looking through all the other log files I could find, I eventually tried running `bpm start` manually and was able to see the error...

```
$ bpm start ipfs
Error: failed to start job-process: failed to create system files: requested persistent disk does not exist
```

A little surprised, I verified I didn't miss the message in a log somewhere else...

```
$ grep -snr 'requested persistent disk does not exist' /var/vcap/sys/log/
```

It kind of makes sense that I could be missing logs since I'm not redirecting the output of my monit start/stop commands like I do with non-bpm jobs... but I also had originally been assuming bpm was redirecting everything possible to its log file.

If an odd edge case like this were to show up in a production environment, it would be difficult to diagnose the issue from logs. Could/should this sort of error something which could be written to the regular `bpm.log` file instead of `STDOUT` only? If not, I start wanting to go back to wrap all my start/stop `bpm` calls so I can be sure that all output will be sent to a log file somewhere... but that's extra overhead I'd prefer to avoid.

Thanks!

**Comment by jfmyers9** [comment]
Thanks for bringing this to our attention. We were missing some critical log lines in both the `start`/`stop` command. The error above should show up in the `/var/vcap/sys/log/<job>/bpm.log` in future releases.
