### ISSUE TITLE
`bpm stop` times out when stopping in a resource constrained environment

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry-incubator/bpm-release#60]
By default, monit imposes a 30 second timeout when running `monit stop` on a process. Right now, `bpm stop` will:
* Send a `SIGTERM` to the process
* If the process does not exit in 20 seconds, send a `SIGQUIT` to the process
* Wait up to 5 seconds for the process to exit
* `runc delete -f` which will send a `SIGKILL` and delete the container
* Delete the runc bundle in `/var/vcap/data/bpm/bundles`

In our upgrade tests, we are seeing that this takes ~30 seconds and causes the `monit stop` to fail:
```
{"timestamp":"1528407119.558125257","source":"bpm","message":"bpm.stop.acquiring-lifecycle-lock.starting","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1.1"}}
{"timestamp":"1528407119.558376551","source":"bpm","message":"bpm.stop.acquiring-lifecycle-lock.complete","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1.1"}}
{"timestamp":"1528407119.558422804","source":"bpm","message":"bpm.stop.starting","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1"}}
{"timestamp":"1528407144.594295740","source":"bpm","message":"bpm.stop.failed-to-stop","log_level":2,"data":{"error":"failed to stop job within timeout","job":"test-server","process":"alt-test-server","session":"1"}}
{"timestamp":"1528407149.619541407","source":"bpm","message":"bpm.stop.complete","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1"}}
{"timestamp":"1528407149.619646311","source":"bpm","message":"bpm.stop.releasing-lifecycle-lock.starting","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1.2"}}
{"timestamp":"1528407149.619714737","source":"bpm","message":"bpm.stop.releasing-lifecycle-lock.complete","log_level":1,"data":{"job":"test-server","process":"alt-test-server","session":"1.2"}}
```

This is due to the fact that `runc delete -f` and deleting the bundle are taking about 5 seconds on top of the 25 seconds that we wait for the process to exit.

We should separate actions that may be IO constrained from `bpm stop`.

A different way to stop processes could be:
* Send a `SIGTERM` to the process
* If the process does not exit in 20 seconds, send a `SIGQUIT` to the process
* If the process does not exit in 5 seconds, send a `SIGKILL` to the process
* Out of band, delete the container and clean up the bundle.

I'm not quite sure what it means to clean up the artifacts "out of band" yet.

Thoughts?

**Comment by xoebus** [comment]
Do we know which part is taking so long? I didn't think we wrote much to disk (the usual culprit).

**Comment by jfmyers9** [comment]
We don't have granular logging, but it's the combo of `runc delete -f` and `rm -rf bundle_path`.
