### ISSUE TITLE
Issue with gorouter allowing users to stream access logs to sys logs

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry-incubator/bpm-release#82]
## Issue
Gorouter fails to deploy with `router.enable_access_log_streaming` set to `true`. 

## Context
The gorouter exposes a spec property to [enable access log streaming]( https://github.com/cloudfoundry/routing-release/blob/f1650b3ae77f1d53fd5cc7f8ca4b91ee25999518/jobs/gorouter/spec#L256). This was exposed as a feature since some users had concerns about writing logs to disk and the performance implication + the volume of logs thereof. There is another property that operators can use to [stop writing access logs to disk](https://github.com/cloudfoundry/routing-release/blob/f1650b3ae77f1d53fd5cc7f8ca4b91ee25999518/jobs/gorouter/spec#L259). 

The gorouter now uses BPM by default and this means that the deploy now fails when the Gorouter is deployed with the `router.enable_access_log_streaming` set to `true`. 

The issue was reported by someone from the community [here](https://github.com/cloudfoundry/routing-release/issues/118) 

## Steps to Reproduce

1. Set `router.enable_access_log_streaming` set to `true` in the deployment manifest
2. Deploy 
3. Deployment fails

## Expected result

Deployment should succeed. 

## Current result

Deployment fails. 

## Possible Options

1. We can deprecate this feature for the gorouter if the performance concerns are mitigated by BPM 
2. We can make this a feature for BPM
3. We can implement this in the Gorouter, though this will be a bespoke implementation and mean that we will diverge from the standard BPM is trying to push across components.

**Comment by xoebus** [comment]
You can write directly to the syslog device by mounting it as a volume for the process. e.g.

```yaml
processes:
- name: gorouter
  ...
  unsafe:
    unrestricted_volumes:
    - path: /dev/log
      mount_only: true
```

**Comment by voelzmo** [comment]
For reference: BOSH has the same issue that we're trying to fix with https://www.pivotaltracker.com/story/show/159191961 by not writing to syslog directly, but use a dedicated file in the filesystem instead.

**Comment by xoebus** [comment]
Going to close this for now but feel free to re-open or message us if this doesn't work.
