### ISSUE TITLE
bpm run -v flag parses multiple options incorrectly

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry-incubator/bpm-release#93]
Whilst experimenting with `bpm run -v ...` in v0.12.0 we discovered that when multiple options are provided in the flag they are parsed incorrectly. For example:

```bash
$ bpm run -p my_process -v /var/vcap/store/my_dir:writeable,mount_only
Error: invalid volume path: mount_only must be within (/var/vcap/data, /var/vcap/store)
```

After inspecting we discovered the issue is in the flag parsing package used here: https://github.com/cloudfoundry-incubator/bpm-release/blob/be92a3b0427d78d4d6c3cb1497a1e485a5ee4127/src/bpm/commands/run.go#L39

`StringSliceVarP` splits flag values on `,`. For example `-v /var/vcap/store/my_dir:writeable,mount_only` is parsed to `[]string{"/var/vcap/store/my_dir:writeable","mount_only"}`.

We're not sure what the best solution is for this issue. Perhaps a different separator for the volume options, or a different flag parser?

Currently we only need to pass a single volume with a single option, so we are not blocked by this issue at the moment.

Josh and @aclevername
cc: @cloudfoundry-incubator/bosh-backup-and-restore-team

**Comment by xoebus** [comment]
@jamesjoshuahill Thanks for the report! I'll take a look today.
